import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

// THIRD-PARTY-LICENSES.md ships inside the installer (electron-builder.yml extraResources).
// It's generated by `npm run licenses:generate`; these checks keep the committed copy honest.
const root = join(__dirname, '..', '..')
const notices = readFileSync(join(root, 'THIRD-PARTY-LICENSES.md'), 'utf8')

interface LockEntry {
  name?: string
  version: string
  dev?: boolean
  devOptional?: boolean
  link?: boolean
}

function productionPackages(): { name: string; version: string }[] {
  const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8')) as {
    packages: Record<string, LockEntry>
  }
  return Object.entries(lock.packages)
    .filter(([path, entry]) => path !== '' && !entry.dev && !entry.devOptional && !entry.link)
    .map(([path, entry]) => ({
      name: entry.name ?? path.split('node_modules/').pop()!,
      version: entry.version
    }))
}

describe('THIRD-PARTY-LICENSES.md', () => {
  it('reproduces licence texts, not an unformatted object (shipped that way from the GPL relicense to v1.3.2)', () => {
    expect(notices).not.toContain('[object Object]')
    // node-simconnect's LGPL text, which the compliance section promises in full.
    expect(notices).toContain('GNU LESSER GENERAL PUBLIC LICENSE')
    expect(notices).toContain('This version of the GNU Lesser General Public License incorporates')
    // A real MIT notice from a shipped package.
    expect(notices).toMatch(
      /### react 19\.\d+\.\d+ — MIT\s+```\s+MIT License\s+Copyright \(c\) Meta Platforms/
    )
  })

  it('lists every production package in package-lock.json, transitive ones included, at its locked version', () => {
    const missing = productionPackages()
      .filter((p) => p.name !== 'node-simconnect') // reproduced in its own LGPL section
      .filter((p) => !notices.includes(`### ${p.name} ${p.version} — `))
      .map((p) => `${p.name}@${p.version}`)
    // Non-empty means a dependency changed without `npm run licenses:generate` being re-run.
    expect(missing).toEqual([])
  })

  it('carries the standard licence text for packages that ship no licence file', () => {
    expect(notices).toMatch(
      /### drizzle-orm [\d.]+ — Apache-2\.0\s+This package declares[^\n]*reproduced below\.\s+```\s+Apache License/
    )
    expect(notices).toMatch(
      /### murmurhash-js [\d.]+ — MIT\s+This package declares[^\n]*reproduced below\.\s+```\s+MIT License\s+Copyright \(c\) Gary Court/
    )
  })

  it('covers all four vendored datasets', () => {
    for (const title of [
      'Airports — OurAirports',
      'Runways — OurAirports',
      'Airlines — OpenFlights (ODbL 1.0)',
      'Aircraft type designators'
    ]) {
      expect(notices).toContain(`### ${title}`)
    }
  })
})
